CREATE TABLE `EmailJob` (
  `id` VARCHAR(191) NOT NULL,
  `type` ENUM('MATCH_REMINDER','PREDICTION_CLOSING','PREDICTIONS_REPORT','MATCH_RESULTS_REPORT') NOT NULL,
  `priority` ENUM('HIGH','MEDIUM','LOW') NOT NULL,
  `status` ENUM('PENDING','SENDING','SENT','FAILED','DEFERRED','DROPPED') NOT NULL DEFAULT 'PENDING',
  `required` BOOLEAN NOT NULL DEFAULT false,
  `recipientEmail` VARCHAR(320) NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `html` LONGTEXT NOT NULL,
  `text` LONGTEXT NOT NULL,
  `dedupeKey` VARCHAR(191) NOT NULL,
  `matchId` VARCHAR(191) NULL,
  `leagueId` VARCHAR(191) NULL,
  `providerKey` VARCHAR(191) NULL,
  `scheduledAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `availableAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lastAttemptAt` DATETIME(3) NULL,
  `attemptCount` INTEGER NOT NULL DEFAULT 0,
  `sentAt` DATETIME(3) NULL,
  `lastError` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `EmailJob_dedupeKey_key`(`dedupeKey`),
  INDEX `EmailJob_status_availableAt_idx`(`status`, `availableAt`),
  INDEX `EmailJob_priority_scheduledAt_idx`(`priority`, `scheduledAt`),
  INDEX `EmailJob_matchId_idx`(`matchId`),
  INDEX `EmailJob_leagueId_idx`(`leagueId`),
  INDEX `EmailJob_providerKey_idx`(`providerKey`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `EmailProviderUsage` (
  `id` VARCHAR(191) NOT NULL,
  `providerKey` VARCHAR(191) NOT NULL,
  `quotaWindowStart` DATETIME(3) NOT NULL,
  `sentCount` INTEGER NOT NULL DEFAULT 0,
  `blockedUntil` DATETIME(3) NULL,
  `lastError` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `EmailProviderUsage_providerKey_quotaWindowStart_key`(`providerKey`, `quotaWindowStart`),
  INDEX `EmailProviderUsage_providerKey_blockedUntil_idx`(`providerKey`, `blockedUntil`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
