CREATE TABLE `EmailProviderAccount` (
  `id` VARCHAR(191) NOT NULL,
  `key` VARCHAR(191) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `fromEmail` VARCHAR(320) NOT NULL,
  `fromName` VARCHAR(191) NULL,
  `smtpHost` VARCHAR(255) NOT NULL,
  `smtpPort` INTEGER NOT NULL DEFAULT 587,
  `secure` BOOLEAN NOT NULL DEFAULT false,
  `smtpUser` VARCHAR(320) NULL,
  `smtpPassEncrypted` LONGTEXT NULL,
  `dailyLimit` INTEGER NOT NULL DEFAULT 100,
  `reservedHighPriority` INTEGER NOT NULL DEFAULT 60,
  `maxRecipientsPerMessage` INTEGER NOT NULL DEFAULT 100,
  `maxEmailSizeMb` INTEGER NOT NULL DEFAULT 35,
  `maxAttachmentSizeMb` INTEGER NOT NULL DEFAULT 25,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `blockedUntil` DATETIME(3) NULL,
  `lastUsedAt` DATETIME(3) NULL,
  `lastError` TEXT NULL,
  `deletedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `EmailProviderAccount_key_key`(`key`),
  INDEX `EmailProviderAccount_active_deletedAt_idx`(`active`, `deletedAt`),
  INDEX `EmailProviderAccount_key_blockedUntil_idx`(`key`, `blockedUntil`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
