CREATE TABLE `EmailBacklogAuditRun` (
  `id` VARCHAR(191) NOT NULL,
  `trigger` ENUM('SCHEDULER','MANUAL','CLI') NOT NULL,
  `mode` ENUM('AUDIT','SANITIZE') NOT NULL,
  `status` ENUM('RUNNING','COMPLETED','FAILED','SKIPPED') NOT NULL DEFAULT 'RUNNING',
  `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `completedAt` DATETIME(3) NULL,
  `durationMs` INTEGER NULL,
  `inspectedCount` INTEGER NOT NULL DEFAULT 0,
  `actionableCount` INTEGER NOT NULL DEFAULT 0,
  `staleSendingCount` INTEGER NOT NULL DEFAULT 0,
  `exhaustedRetryCount` INTEGER NOT NULL DEFAULT 0,
  `transientWithinBudgetCount` INTEGER NOT NULL DEFAULT 0,
  `sanitizedCount` INTEGER NOT NULL DEFAULT 0,
  `deferredCount` INTEGER NOT NULL DEFAULT 0,
  `failedCount` INTEGER NOT NULL DEFAULT 0,
  `droppedCount` INTEGER NOT NULL DEFAULT 0,
  `notActionedCount` INTEGER NOT NULL DEFAULT 0,
  `errorCount` INTEGER NOT NULL DEFAULT 0,
  `summary` JSON NULL,
  `errorMessage` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  INDEX `EmailBacklogAuditRun_startedAt_idx`(`startedAt`),
  INDEX `EmailBacklogAuditRun_status_startedAt_idx`(`status`, `startedAt`),
  INDEX `EmailBacklogAuditRun_trigger_startedAt_idx`(`trigger`, `startedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
